// AURELIA LUXE - Demifine® Jewellery Product Database
// Curated & Designed by Jagruti Patil

const PRODUCTS_DATA = [
  {
    id: "aur-001",
    title: "Hearts All Over Charm Bracelet",
    subtitle: "18K Thick Gold Vermeil | Waterproof & Anti-Tarnish",
    category: "bracelets",
    price: 999,
    originalPrice: 1999,
    rating: 4.9,
    reviewCount: 384,
    badge: "FLAT ₹999",
    badges: ["FLAT ₹999", "WATERPROOF", "BESTSELLER"],
    image: "https://images.unsplash.com/photo-1611591475155-426c043e480b?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    description: "Delicate interlocking heart charms suspended on a shimmering paperclip chain. Finished with 2.5 microns of real 18K gold vermeil over hypoallergenic surgical steel. Designed to be worn to sleep, shower, and conquer everyday life.",
    material: "18K Gold Vermeil over 316L Surgical Grade Steel",
    weight: "4.8g",
    length: "16cm + 4cm adjustable extender",
    isBestSeller: true,
    isNew: false,
    isUnder999: true,
    tag: "Trending"
  },
  {
    id: "aur-002",
    title: "Athena Solitaire Huggie Hoops",
    subtitle: "SGL Certified Lab Diamond Simulant | 18K Gold",
    category: "earrings",
    price: 1199,
    originalPrice: 2399,
    rating: 5.0,
    reviewCount: 512,
    badge: "BESTSELLER",
    badges: ["BESTSELLER", "SKIN-SAFE", "18K GOLD"],
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    description: "The ultimate everyday hoops that you will never take off. Ultra-comfortable clicker clasp with a brilliant cut round solitaire that catches every ray of sunlight. 100% nickel-free and zero itchiness.",
    material: "18K Gold Plated over 925 Sterling Silver, Grade 5A Zirconia",
    weight: "3.2g pair",
    diameter: "14mm outer, 11mm inner",
    isBestSeller: true,
    isNew: false,
    isUnder999: false,
    tag: "Celebrity Pick"
  },
  {
    id: "aur-003",
    title: "Sarvani Modern Mangalsutra Bracelet",
    subtitle: "Traditional Black Beads with Contemporary Flair",
    category: "mangalsutra",
    price: 1499,
    originalPrice: 2999,
    rating: 4.9,
    reviewCount: 428,
    badge: "MOST LOVED",
    badges: ["MOST LOVED", "MODERN TRADITION", "WATERPROOF"],
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    description: "Tradition modernised for the woman on the move. Micro-set black spinel beads paired with an infinity motif plated in thick 18k gold. Sits comfortably on your wrist without tangling or scratching.",
    material: "18K Gold Vermeil, Natural Black Spinel Beads",
    weight: "5.1g",
    length: "17cm + 3cm extender",
    isBestSeller: true,
    isNew: false,
    isUnder999: false,
    tag: "Bestseller"
  },
  {
    id: "aur-004",
    title: "Crystal Affair Tennis Bracelet",
    subtitle: "Endless Radiance | Micro-Pavé Prong Setting",
    category: "bracelets",
    price: 1399,
    originalPrice: 2799,
    rating: 4.8,
    reviewCount: 290,
    badge: "EXTRA 40% OFF",
    badges: ["EXTRA 40% OFF", "18K GOLD", "GLAM"],
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1611591475155-426c043e480b?auto=format&fit=crop&w=800&q=80",
    description: "Channel high-society glamour with this flexible tennis bracelet. Each stone is precision cut and individually claw-set to give the fiery sparkle of genuine mined diamond tennis bracelets.",
    material: "Thick 18K Gold Finish, Grade AAA Austrian Crystals",
    weight: "8.5g",
    length: "18cm with double security box clasp",
    isBestSeller: true,
    isNew: false,
    isUnder999: false,
    tag: "Party Edit"
  },
  {
    id: "aur-005",
    title: "Celestial Sunburst Pendant Necklace",
    subtitle: "Dainty Cable Chain with Radiating Sun Motif",
    category: "necklaces",
    price: 1299,
    originalPrice: 2599,
    rating: 5.0,
    reviewCount: 315,
    badge: "SHIPS IN 24H",
    badges: ["SHIPS IN 24H", "WATERPROOF", "NEW DROP"],
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    description: "A symbol of warmth, power, and optimism. The central bezel-set crystal radiates textured rays of gold. Perfect for standalone wear or stacking with our Herringbone snake chain.",
    material: "18K Gold Vermeil on Solid 925 Sterling Silver",
    weight: "4.2g",
    length: "42cm + 5cm extension",
    isBestSeller: false,
    isNew: true,
    isUnder999: false,
    tag: "New Arrival"
  },
  {
    id: "aur-006",
    title: "Solitaire Crown Engagement Ring",
    subtitle: "1.5 Carat Radiant Solitaire with Pavé Band",
    category: "rings",
    price: 999,
    originalPrice: 2199,
    rating: 4.9,
    reviewCount: 640,
    badge: "FLAT ₹999",
    badges: ["FLAT ₹999", "ANTI-TARNISH", "BESTSELLER"],
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80",
    description: "Stunning four-prong crown holding an ultra-clear, brilliant lab-grown diamond simulant. The inner comfort-fit curved band guarantees irritation-free wear all day.",
    material: "Platinum Plated 925 Sterling Silver / 18K Yellow Gold Tone",
    weight: "2.8g",
    sizes: ["US 5", "US 6", "US 7", "US 8", "Adjustable"],
    isBestSeller: true,
    isNew: false,
    isUnder999: true,
    tag: "Bestseller"
  },
  {
    id: "aur-007",
    title: "Signature Nail Statement Bangle",
    subtitle: "Iconic Curved Nail Motif with Crystal Accent",
    category: "bracelets",
    price: 1599,
    originalPrice: 3199,
    rating: 4.9,
    reviewCount: 188,
    badge: "LUXE EDIT",
    badges: ["LUXE EDIT", "WATERPROOF", "HYPOALLERGENIC"],
    image: "https://images.unsplash.com/photo-1611591475155-426c043e480b?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=80",
    description: "Bold, daring, and unapologetically fashionable. Inspired by luxury runway trends, this cuff snaps securely around your wrist and maintains its high mirror polish through workouts and showers.",
    material: "Grade 316L Surgical Titanium Steel, 18K PVD Gold Plating",
    weight: "18.2g",
    diameter: "6.0cm inner diameter (fits wrist 15-18cm)",
    isBestSeller: false,
    isNew: true,
    isUnder999: false,
    tag: "Runway Style"
  },
  {
    id: "aur-008",
    title: "Chevron Eternity Stacking Ring",
    subtitle: "V-Contoured Wishbone Design for Ring Stacking",
    category: "rings",
    price: 899,
    originalPrice: 1799,
    rating: 4.8,
    reviewCount: 220,
    badge: "UNDER ₹999",
    badges: ["UNDER ₹999", "18K GOLD", "STACKABLE"],
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    description: "Designed specifically to hug solitaire rings or be stacked in a trio. The geometric pointed V-shape visually elongates your fingers while giving a refined modern glow.",
    material: "18K Yellow Gold Vermeil on Sterling Silver",
    weight: "1.9g",
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9"],
    isBestSeller: true,
    isNew: false,
    isUnder999: true,
    tag: "Budget Chic"
  },
  {
    id: "aur-009",
    title: "Twin Heart Interlocking Silver Necklace",
    subtitle: "Fine Platinum Plated 925 Sterling Silver",
    category: "necklaces",
    price: 1499,
    originalPrice: 2999,
    rating: 4.9,
    reviewCount: 365,
    badge: "FINE SILVER",
    badges: ["FINE SILVER", "PLATINUM COATED", "ROMANTIC"],
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    description: "Two intertwined hearts representing inseparable love. One heart is finished with mirror polished platinum silver, while the other sparkles with micro-pavé cubic stones.",
    material: "925 Pure Sterling Silver coated with Rhodium / Platinum",
    weight: "3.9g",
    length: "40cm + 5cm adjustable",
    isBestSeller: true,
    isNew: false,
    isUnder999: false,
    tag: "Gifting Special"
  },
  {
    id: "aur-010",
    title: "Mystic Evil Eye Protection Necklace",
    subtitle: "Deep Cobalt Blue Enamel with Diamond Halo",
    category: "necklaces",
    price: 1199,
    originalPrice: 2399,
    rating: 5.0,
    reviewCount: 410,
    badge: "BESTSELLER",
    badges: ["BESTSELLER", "WARD OFF EVIL", "DAILY WEAR"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    description: "Ward off negative vibes in radiant style. Hand-painted Greek blue enamel with a sparkling pupil stone framed in an 18K gold sunshine halo. Sweat-resistant and lightweight.",
    material: "18K Gold Tone on Surgical Steel, Hand Enamelled",
    weight: "3.7g",
    length: "45cm + 5cm extension",
    isBestSeller: true,
    isNew: false,
    isUnder999: false,
    tag: "Ward Off Negativity"
  },
  {
    id: "aur-011",
    title: "Men's Sovereign Cuban Link Chain",
    subtitle: "Heavy Gauge 6mm Diamond Cut Curb Links",
    category: "mens",
    price: 1699,
    originalPrice: 3399,
    rating: 4.9,
    reviewCount: 195,
    badge: "MEN'S LUXE",
    badges: ["MEN'S LUXE", "ANTI-TARNISH", "HEAVY GAUGED"],
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1611591475155-426c043e480b?auto=format&fit=crop&w=800&q=80",
    description: "Solid, confident, and meticulously beveled. Made for the modern gentleman who values quiet luxury. Built to survive gym workouts, sea water, and daily wear without dulling.",
    material: "Industrial Strength 316L Steel with 18K Real Gold PVD Ion Plating",
    weight: "26g",
    length: "55cm (22 inches)",
    isBestSeller: true,
    isNew: false,
    isUnder999: false,
    tag: "Men's Collection"
  },
  {
    id: "aur-012",
    title: "Baroque Freshwater Pearl Drop Earrings",
    subtitle: "Lustrous Organic Pearls on 18K Gold Hooks",
    category: "earrings",
    price: 1249,
    originalPrice: 2499,
    rating: 4.8,
    reviewCount: 140,
    badge: "NATURAL PEARLS",
    badges: ["NATURAL PEARLS", "HANDMADE", "LUXE"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80",
    description: "Organic, one-of-a-kind freshwater cultured pearls with iridescent luster. Dangled on French wire hooks crafted in 18k thick gold plating. Ultra light on the lobes.",
    material: "Genuine Freshwater Cultured Pearls, 18K Gold Plated 925 Silver",
    weight: "4.5g pair",
    length: "3.2cm total drop",
    isBestSeller: false,
    isNew: true,
    isUnder999: false,
    tag: "Editorial"
  },
  {
    id: "aur-013",
    title: "Liquid Gold Herringbone Choker",
    subtitle: "Ultra-Flexible Silk Snake Chain That Glides Like Silk",
    category: "necklaces",
    price: 999,
    originalPrice: 1999,
    rating: 5.0,
    reviewCount: 472,
    badge: "FLAT ₹999",
    badges: ["FLAT ₹999", "WATERPROOF", "TRENDING"],
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    description: "A ribbon of 18K gold that drapes smoothly against your collarbone like molten metal. Does not kink, pinch, or pull hair. The number one layering staple of the season.",
    material: "18K Gold Vermeil on Surgical Stainless Steel",
    weight: "7.1g",
    length: "38cm + 6cm adjustable chain",
    isBestSeller: true,
    isNew: false,
    isUnder999: true,
    tag: "Viral Favorite"
  },
  {
    id: "aur-014",
    title: "Bhavani Solitaire Infinity Mangalsutra",
    subtitle: "Sacred Black Beads with Brilliant Infinity Pendant",
    category: "mangalsutra",
    price: 1799,
    originalPrice: 3599,
    rating: 4.9,
    reviewCount: 308,
    badge: "LIFETIME RE-PLATE",
    badges: ["LIFETIME RE-PLATE", "SACRED SYMBOL", "18K GOLD"],
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    description: "Representing infinite love and protection. Subtle enough to wear with western blazers and formal sarees alike. Comes with authentic 1-year anti-fade guarantee.",
    material: "18K Thick Gold Vermeil, 925 Sterling Silver, Grade 5A Zirconia",
    weight: "6.4g",
    length: "42cm",
    isBestSeller: true,
    isNew: false,
    isUnder999: false,
    tag: "Bridal Edit"
  },
  {
    id: "aur-015",
    title: "Croissant Dome Textured Statement Ring",
    subtitle: "French Parisian Ribbed Tapered Band",
    category: "rings",
    price: 999,
    originalPrice: 1999,
    rating: 4.8,
    reviewCount: 165,
    badge: "FLAT ₹999",
    badges: ["FLAT ₹999", "WATERPROOF", "COMFORT FIT"],
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80",
    description: "Bold volume without the heavy solid gold price tag. Smooth sculpted ridges inspired by Parisian bakeries. Completely hollowed inside for ergonomic feather-weight comfort.",
    material: "18K Gold Vermeil over Hypoallergenic Stainless Steel",
    weight: "5.4g",
    sizes: ["US 6", "US 7", "US 8", "Adjustable"],
    isBestSeller: false,
    isNew: true,
    isUnder999: true,
    tag: "Parisian Chic"
  },
  {
    id: "aur-016",
    title: "Men's Minimalist Signet Ring",
    subtitle: "Brushed Satin Finish with Chamfered Edges",
    category: "mens",
    price: 1199,
    originalPrice: 2399,
    rating: 4.9,
    reviewCount: 142,
    badge: "MEN'S LUXE",
    badges: ["MEN'S LUXE", "ANTI-SCRATCH", "CLEAN MINIMAL"],
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    description: "Understated masculine elegance. Features a matte brushed rectangular face and polished beveled edges that won't snag on clothing. Durable enough for daily manual work.",
    material: "Heavy Duty 316L Stainless Steel with 18K Yellow Gold / Platinum Plating",
    weight: "9.8g",
    sizes: ["US 8", "US 9", "US 10", "US 11"],
    isBestSeller: false,
    isNew: false,
    isUnder999: false,
    tag: "Men's Signature"
  }
];

// Verified Customer Reviews Database
const REVIEWS_DATA = [
  {
    author: "Ananya Deshmukh",
    city: "Mumbai",
    rating: 5,
    title: "Looks and feels exactly like 22k gold!",
    comment: "I have been wearing the Hearts All Over Bracelet every single day for 4 months now — in the shower, gym, and office. Not a speck of tarnishing or green skin! Truly comparable to Palmonas at an even better craft level. Proud of Jagruti Patil's curation!",
    productName: "Hearts All Over Charm Bracelet",
    verified: true,
    date: "2 days ago"
  },
  {
    author: "Rohan Malhotra",
    city: "Delhi NCR",
    rating: 5,
    title: "Best men's chain in India hands down",
    comment: "Most gold plated chains turn brassy copper in 2 weeks. The Sovereign Cuban Chain from Aurelia Luxe is heavy, super premium, and survived swimming pool chlorinated water with zero fading. Insane value.",
    productName: "Men's Sovereign Cuban Link Chain",
    verified: true,
    date: "1 week ago"
  },
  {
    author: "Pooja Hegde",
    city: "Bengaluru",
    rating: 5,
    title: "The modern mangalsutra is a gamechanger",
    comment: "I was looking for a daily wear mangalsutra that doesn't feel like a heavy traditional bridal necklace. This Sarvani bracelet is so delicate and chic! My colleagues all asked me where I bought it.",
    productName: "Sarvani Modern Mangalsutra Bracelet",
    verified: true,
    date: "2 weeks ago"
  },
  {
    author: "Simran Kaur",
    city: "Chandigarh",
    rating: 5,
    title: "Unbelievable shine on the Athena Hoops",
    comment: "I have ultra sensitive ears that react to anything less than solid 18K gold. These earrings caused zero redness, irritation, or soreness even when sleeping in them. 10/10 recommend Aurelia Luxe!",
    productName: "Athena Solitaire Huggie Hoops",
    verified: true,
    date: "3 weeks ago"
  }
];
